[package]
name = "scarf"
version = "0.2.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]

[profile.release]
debug = true

[dependencies]
byteorder = "1.1.0"
hex-slice = "0.1.0"
lde = "0.2.0"
log = "0.3.8"
quick-error = "1.2.0"
serde = { version = "1.0.11", features = ["rc"] }
serde_derive = "1.0.11"
smallvec = "0.5"
