[package]
name = "scarf"
version = "0.3.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[[bin]]
name = "scarf-cfg"
path = "src/bin/scarf-cfg.rs"
required-features = ["binaries"]

[dependencies]
byteorder = "1.1.0"
fxhash = "0.2"
lde = { git = "https://github.com/CasualX/lde" }
log = "0.4"
quick-error = "1.2.0"
serde = { version = "1.0.11", features = ["rc"] }
serde_derive = "1.0.11"
smallvec = "0.6"

clap = { version = "2.27.1", optional = true }

[features]
binaries = ["clap"]
fuzz = []
